### ISSUE TITLE
Allow optional params to be checked with default=None, in addition to using the Optional type hint

### ISSUE THREAD

**Issue by dblakely** [lebrice/SimpleParsing#132]
**Is your feature request related to a problem? Please describe.**

It's common to have args in a dataclass that are optional but aren't explicitly typed as such via the `Optional` type hint. For example:

```python
from dataclasses import dataclass, field
from simple_parsing import ArgumentParser

@dataclass
class Args:
    x: int = field(default=None)

parser = ArgumentParser()
parser.add_arguments(Args, dest="args")
args = parser.parse_args().args
```

In this case, `Args.x` is clearly intended to be optional despite not having an `Optional` type hint. However, if you run this you'll get `error: the following arguments are required: -x/--x`. In order to run this, you have to change the line with `x` to be `x: Optional[int] = field(default=None)`. 

Of course, this is an easy change to make, but it's a little tedious, especially as many developers don't bother using `Optional` because it's kind of redundant with simply setting the default value to `None`. 

But even beyond that, it would be nice to use `simple_parsing` with, say, the Huggingface's `TrainingArguments` class from the `transformers` library. However, that's currently not possible because that class contains lines of code like [this one](https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L563), where you have optional args that don't use the `Optional` type hint. 

**Describe the solution you'd like**

Can we instead determine if an arg is optional by just checking if the default value inside the field is `None`? 

If needed, I can volunteer to help make this change!

**Comment by lebrice** [comment]
Hello @dblakely , thanks for pointing this out!

Yeah sure, that sounds like a good idea. 

I'd like to point out though that these field annotations aren't valid, from a type-checker's perspective: the arguments _are_ optional, and so the value should be either `int | None` or `Optional[int]`. 

I agree with you, it sounds totally reasonable to consider them as Optional for simple-parsing though.

This should be a quite simple fix as well: I think that this is probably all that needs to be changed:
###
https://github.com/lebrice/SimpleParsing/blob/009a6013be2c72547116cfc3cfeb9e360d31ebc5/simple_parsing/wrappers/field_wrapper.py#L231
### 

This should be:
```python
    elif utils.is_optional(self.type) and self.field.default is not None:
```

This sounds like a simple, and potentially very useful contribution! Let me know if you run into any issues, and I'll be happy to help :)


Thanks again!

**Comment by dblakely** [comment]
Thanks @lebrice! I'll take a look at it and let you know if I have any issues.

**Comment by joel-odlund** [comment]
this seems to be an important feature.
In the mean time, is there a workaround to have None as a default value for an optional parameter?
