### ISSUE TITLE
Drop support for python 3.6

### ISSUE THREAD

**Issue by lebrice** [lebrice/SimpleParsing#135]
I'm seriously considering dropping support for python 3.6:
- It's making it quite difficult to write new features based on more recent members of the typing module.
- I prefer to use postponed evaluation of type annotations whenever possible, and the `A | B` syntax rather than `Union[A, B]`.

Does anyone have any strong objections to this?

If not, I'll go ahead with this soon (e.g. 1-2 weeks), and bump the minor version in the next release, to signify this change.

**Comment by idoby** [comment]
I think it's safe to assume people who use this also use the latest (or almost-latest) version of Python
