### ISSUE TITLE
Support Optional to allow truly optional arguments

### ISSUE THREAD

**Issue by Wooza** [lebrice/SimpleParsing#14]
**Is your feature request related to a problem? Please describe.**
I'm creating a tool that can be seeded. But if no seed is given, then i will just take a random seed.
The problem that I'm currently facing is that I can only define the seed as int and therefore cannot set it to None as default.
```
class Config:
    seed: int = 42
```

**Describe the solution you'd like**
I would like to be able to use something like this:
```
class Config:
    seed: Optional[int] = None
```
But this crashes the help generation

**Describe alternatives you've considered**
My current workaround is to use a certain magic value for the seed to indicate that it was not defined via the command line arguments.

Also, really nice library 👍

**Comment by lebrice** [comment]
Thanks a lot @Wooza  for making this issue! I'll get right on it!

**Comment by Wooza** [comment]
Thanks for implementing this feature and putting out a new release 😃
