### ISSUE TITLE
Fix the Logging config.

### ISSUE THREAD

**Issue by lebrice** [lebrice/SimpleParsing#21]
**Describe the bug**
Not sure how, but there might be a smarter way to configure the logging so as not to pollute the output of whatever code is using simple_parsing, following [https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library)

**Comment by wolf1986** [comment]
Hi! Thanks for the nice library!

I've noticed a problem with logging - it wasn't done the standard way, and was hard to integrate into projects with other loggers.

Added more info & explanations in this PR: #79
