### ISSUE TITLE
Support for parallel commands

### ISSUE THREAD

**Issue by comfortablynick** [lebrice/SimpleParsing#22]
**Is your feature request related to a problem? Please describe.**
Argparse has no native support for multiple parallel commands. This would be a great addition to this dataclass based parser.

**Describe the solution you'd like**
An example is an image processing tool. It would be great to be able to do this:

```python
img.py --input ~/image.jpg resize --scale 0.5 sharpen --radius 0.2 save --quality 85 --file ~/image_edited.jpg
```

**Describe alternatives you've considered**
Declarative Parser [supports](https://github.com/krassowski/declarative-parser#nested-and-parallel) this, but I find your dataclass based parser and strong typing appealing.

**Additional context**
Click also [supports](https://github.com/pallets/click/tree/master/examples/imagepipe) this, but I'd prefer something that integrates with argparse.

**Comment by lebrice** [comment]
Hi there! Thanks a lot for posting this. Let me think about this a little bit and I'll get back to you.

**Comment by lebrice** [comment]
Hi @comfortablynick ! Sorry for taking so long to respond.
I've got [a little branch setup with some example code](https://github.com/lebrice/SimpleParsing/blob/commands_example/examples/commands/commands_example.py) which might be useful in implementing what you're describing: 


Basically the gist of it is, I think this is a great idea, but I don't think it would make sense to place the burden of managing multiprocess/multithread code in the argument parser itself. I think this should more likely be taken care of by user code, which I've illustrated to some extent above.

Also, I'm not quite sure how using multiple subparser actions (using the `resize`, `sharpen` and `save` would work with argparse, do you know of any example where this is working? Does something like Click support that?

Thanks, and I hope this helps somewhat.

**Comment by comfortablynick** [comment]
Thanks, I'll take a look!

I've been working on the utility I mentioned using `argparse` with some custom pre-parsing and subclassing to make it fit my needs. Ultimately, I didn't like how Click did it so I stuck with `argparse`.

[pyimgtool](https://github.com/comfortablynick/pyimgtool/blob/master/pyimgtool/args.py)

I'm sure it's not the most eloquent code, but I figured out a way to make it work. I love the idea of using `dataclass` in argument parsing, so I was hoping to combine the two.

**Comment by lebrice** [comment]
Hi @comfortablynick I'm gonna close this issue, as I don't think this feature would be implemented in simple-parsing, but rather in the user code. Please let me know if you think this should be reopened.
Thanks again for sharing!
