### ISSUE TITLE
Allow to skip a field registration

### ISSUE THREAD

**Issue by Conchylicultor** [lebrice/SimpleParsing#244]
In the dataclass, it is possible to have field which should not be exposed in the CLI. It would be nice to have a way to skip registering those flags:

```python
@dataclass
class A:
  x: int
  y: int = simple_parsing.field(register=False)
```

Then `--x` would be detected, but not `--y`:

```sh
my_program --x=1  # Works
my_program --y=1  # Error: Unknown FLAG --y
```

**Comment by zhiruiluo** [comment]
The dataclasses.field(init=False) would do the thing. If you use that and wanna init this field, you could still initialize it in __post_int__ function.

**Comment by lebrice** [comment]
Hello @Conchylicultor !

Yes there is something like this, you can use `simple_parsing.field(cmd=False)`.

Hope this helps!

**Comment by lebrice** [comment]
I'll close this if that's alright with you. LMK if you have any other questions @Conchylicultor .

Thanks again for posting!

**Comment by Conchylicultor** [comment]
Awesome! Thank you for the quick answer
