### ISSUE TITLE
Bug: unexpected keyword argument not detected when nesting dataclasses

### ISSUE THREAD

**Issue by RmZeta2718** [lebrice/SimpleParsing#295]
**Describe the bug**
Normally, parser should raise an error when unexpected keyword argument occurs. But when dataclasses are nested, it doesn't raise an error but simply omits the unexpected keyword argument.

**To Reproduce**

`test.py`:

```python
from dataclasses import dataclass
import simple_parsing

@dataclass
class ConfigNested:
    a: str = "hello"

@dataclass
class Config:
    config_nested: ConfigNested

args = simple_parsing.parse(Config, add_config_path_arg=True)
print(args)
```

`config.yaml`:

```yaml
config_nested:
  a: world
  b: 123
```

**Expected behavior**
```console
$ python test.py --config_path config.yaml
Traceback (most recent call last):

......

TypeError: ... got an unexpected keyword argument 'b'
```

**Actual behavior**
Omits unexpected keyword argument 'b' and exit successfully:

```console
$ python test.py --config_path config.yaml
Config(config_nested=ConfigNested(a='world'))
```

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - Python version: 3.10.12
 - simple-parsing: 0.1.4

**Comment by stas00** [comment]
@lebrice, I was just about to make the same feature request.

If one makes a typo in a nested key - it just gets ignored and the default is used.

could simple-parsing plug https://github.com/pydantic/pydantic or something similar and provide a strict validation for all keys and values and not only the top-level ones?

This is currently a very big problem since if one makes a typo a whole training could be derailed and not noticed.

Thank you

**Comment by lebrice** [comment]
Thanks for posting!

Hmm this is not intended to happen, good catch!

**Comment by lebrice** [comment]
Hey there @RmZeta2718 @stas00 , sorry for the delay.

I'm working on reproducing / fixing the issue in #301 , but it seems like the latest release fixed this and a `RuntimeError` is now raised when there is an unexpected kwarg in the config. (I don't remember explicitly fixing this though :shrug: )

Could you please check if the latest release also fixes that for you? If not, could you perhaps share an example that isn't working (where no exception is raised?)

Thanks a lot!
