### ISSUE TITLE
pyyaml dependency missing in setup.py

### ISSUE THREAD

**Issue by berendbaas** [lebrice/SimpleParsing#30]
Not sure if this is the intended behavior (and viewed as an optional install), but since pyyaml isn't marked as a dependency, in setup.py, calling .save("...yaml") or .save_yaml on a Serializable data class will crash, due to the missing package. If it is intended to be optional, perhaps it's a good idea to mark it as such in the Readme?

Love the library btw! 👍

**Comment by lebrice** [comment]
Thanks for posting!

Indeed its an optional install, which is only needed when dealing with yaml files. I'll write it somewhere in the Readme.

Thanks! I'm happy you find it useful! Do you mind me asking what kind of features you like / what you think might be missing? I'm trying to gather feedback at the moment..

**Comment by berendbaas** [comment]
Serialization & the ability to not have to compose different sets of options for different scripts in a parser, are probably the most appreciated features for me. It avoids the situation of having one giant argument parser, that ends up being a glorified global namespace where all the settings of are stored.

When it comes to improvements, the following spring to mind:

### Subparsers
I have some scripts where I'm using the [subparsers](https://github.com/lebrice/SimpleParsing/blob/master/examples/subparsers/README.md) functionality. However, some of these tasks don't take any arguments. It feels a bit clunky to have to define a dataclass, just to fit in.
Example:
```python
@dataclass
class ProgramOptions:
    opts: Union[TrainTaskOptions, AnalyseTaskFakeOptions] = subparsers({
        'train': TrainTaskOptions,
        'analyse': AnalyseTaskFakeOptions
    })

@dataclass
class TrainTaskOptions:
    learning_rate: 0.001

@dataclass
class AnalyseTaskFakeOptions:
    # This is basically just a stub, to be able to execute 'script.py analyse' as a subtask
    pass
```
### Saving & Loading Arguments
The other thing that comes to mind is dealing with saving & loading arguments. The way I currently implement this (And I'd love to be wrong about this), is to take a --options-file argument. If this argument is passed a yamlfile, I load and overwrite the options dataclass instance with the loaded data. This however has some downsides:
1) I have to choose between making all arguments optional (as they are not relevant when loading from a file), meaning I have to fall back to manual asserts, making for not-so-nice error messages if no yaml file is passed, and arguments are ommitted.

2) I can't parse a subentry of a yaml file, Illustrated in the example below
```python
# ======================================
# This is for example in a my_network python package
@dataclass
class NetworkOptions(Serializable):
    num_layers: int
    output_dimension: int
    input_dimensions: (int, int)

# ======================================
# this is in my local train-network.py script
from my_network import NetworkOptions

@dataclass
class TrainingScriptOptions(Serializable):
    learning_rate: float
    network_options: NetworkOptions


def train_network():
    options = TrainingScriptOptions()
    options.save_yaml('train-settings.yaml')

# ======================================
# This is in my local analyze-training-settings.py script
from my_network import NetworkOptions

@dataclass
class StubJustForLoadingOptions(Serializable):
    network_options: NetworkOptions


def analyze_training_settings():
    # This won't work
    NetworkOptions.load_yaml('train-settings.yaml', drop_extra_fields=True)

    # So I have to do this
    StubJustForLoadingOptions.load_yaml('train-settings.yaml').network_options

    # It would be nicer if I could do something like this
    NetworkOptions.load_yaml('train-settings.yaml', parse_subpath='network_options')
    pass
```

I'm not a native in python, so I could be missing obvious solutions to these problesm, and they are admittedly relatively minor issues. But they might be worth looking into.

**Comment by lebrice** [comment]
Thanks @berendbaas  for the message. I'll take a good look at it and get back to you. For now I marked the original issue above as documentation/low-priority.

Yes you're right, there is a bit of a pain point when using dataclasses without default field values and nesting, and I think #28 is also pointing this out.

I'll take a closer look and try to replicate your example above, and I'll get back to you, hopefully in the next few days.

**Comment by lebrice** [comment]
Hi @berendbaas , sorry it took a long while to get back to you.

I added a test to reproduce the example you give above, which you can find here:  [https://github.com/lebrice/SimpleParsing/blob/issue-30/test/utils/test_issue_30.py](https://github.com/lebrice/SimpleParsing/blob/issue-30/test/utils/test_issue_30.py)

```python
from simple_parsing import Serializable
from typing import Tuple
from dataclasses import dataclass

@dataclass
class NetworkOptions(Serializable):
    num_layers: int
    output_dimension: int
    input_dimensions: Tuple[int, int]


def test_issue_30(tmpdir):
    network = NetworkOptions(num_layers=10, output_dimension=4, input_dimensions=(16, 16))
    print(network.to_dict())
    network.save(f"{tmpdir}/train-settings.yaml")
    network_ = NetworkOptions.load_yaml(f"{tmpdir}/train-settings.yaml")

    assert network == network_
```

There doesn't seem to be a problem with this code, and it works fine. Maybe I didn't quite get your example reproduced right? Let me know what you think.
