### ISSUE TITLE
Help does not appear if using metadata in fields

### ISSUE THREAD

**Issue by otaj** [lebrice/SimpleParsing#48]
**Describe the bug**
Hi, it seems, that when the dataclass has metadata defined through `field` (from `simple_parsing`, of course), the help in form of comments does not get picked up.

**To Reproduce**
```python
from simple_parsing import ArgumentParser, field
from dataclasses import dataclass

@dataclass
class InputArgs:
    # Start date from which to collect data about base users. Input in iso format (YYYY-MM-DD).
    # The date is included in the data
    start_date: str = field(alias="s", metadata={'a':'b'})

    # End date for collecting base users. Input in iso format (YYYY-MM-DD). The date is included in the data.
    # Should not be before `start_date`
    end_date: str = field(alias="e")

def parse_args() -> InputArgs:
    parser = ArgumentParser("Prepare input data for training")
    parser.add_arguments(InputArgs, dest="args")

    args = parser.parse_args()
    return args.args

if __name__ == "__main__":
    parsed_args = parse_args()
    print(parsed_args)
```

`python test.py -h`

## Output
```
usage: Prepare input data for training [-h] -s str -e str

optional arguments:
  -h, --help            show this help message and exit

InputArgs ['args']:
  InputArgs(start_date: str, end_date: str)

  -s str, --start_date str
  -e str, --end_date str
                        Start date from which to collect data about base
                        users. Input in iso format (YYYY-MM-DD). The date is
                        included in the data End date for collecting base
                        users. Input in iso format (YYYY-MM-DD). The date is
                        included in the data. Should not be before
                        `start_date` (default: None)
```
## Expected output:
```
usage: Prepare input data for training [-h] -s str -e str

optional arguments:
  -h, --help            show this help message and exit

InputArgs ['args']:
  InputArgs(start_date: str, end_date: str)

  -s str, --start_date str
                        Start date from which to collect data about base
                        users. Input in iso format (YYYY-MM-DD). The date is
                        included in the data (default: None)
  -e str, --end_date str
                        End date for collecting base users. Input in iso
                        format (YYYY-MM-DD). The date is included in the data.
                        Should not be before `start_date` (default: None)
```

**Comment by otaj** [comment]
I just did a bit more of a debugging and it seems to be because of [this](https://github.com/lebrice/SimpleParsing/blob/master/simple_parsing/docstring.py#L85) function.
Overall checking if there is only one colon in the code portion of the code line just seems like it's asking for trouble, especially if it seems to be used for checking, if the attribute is defined on a particular line. Isn't there a better way of checking if the line is attribute? (I genuinely don't know)

**Comment by lebrice** [comment]
That's a really juicy little bug you found there @otaj! Thanks a lot for posting! I'll try to get back to you as soon as I can.

**Comment by lebrice** [comment]
To answer your question, that whole docstring feature feels a bit like using forbidden magic at times, so I'm just basing it on my understanding that a field definition looks something like `field: type_annotation = something_something(<something>)`.

I added a check so that it only considers what's in front of the first equal sign in the line, and [this tests](https://github.com/lebrice/SimpleParsing/blob/lebrice/issue48/test/test_issue_48.py) I added to reproduce your issue is passing, so I should be able to deploy a new version to PyPI soon.

Thanks again for posting!

**Comment by otaj** [comment]
Thank you for such a quick resolution!

If I may suggest, how to check for attribute - you know the attribute AND its type (it is part of the `dataclasses.Field`), so how about you check for strings in form `name[ ]:[ ]type`, such that they a) appear only in the class definition (so no more indent than one level) and b) at the beginning of the line (of course, compensated for the indent).

The reason I'm suggesting that is that when I was debugging the problem, I found out, that also lines, that were inside a `__post_init__` method would be triggered by function `_contains_attribute_definition`, which, as stated above, seems like asking for trouble.

Anyway, thanks again :)
