### ISSUE TITLE
Set subparser default value

### ISSUE THREAD

**Issue by Conchylicultor** [lebrice/SimpleParsing#52]
I would like to use subparser with a default value:

I tried:

```python
@dataclasses.dataclass
class Program:
    command: Union[Command0, Command1] = DefaultCommand()

    def execute(self) -> None:
        return self.command.execute()


parser = simple_parsing.ArgumentParser()
parser.add_arguments(Program, dest="program")
parser.parse_args()
```

And 

```python
parser = simple_parsing.ArgumentParser()
parser.add_arguments(Program, dest="program")
parser.set_defaults(**{"program.command": lambda _: parser.print_help()})
parser.parse_args()
```

But none of them seems to work.  Running `python my_program.py` currently raise:

```
error: the following arguments are required: program.command
```

How can this be achieved ?
This can be helpful, for example to display `parser.print_help()` if no command is provided.

**Comment by lebrice** [comment]
Hello @Conchylicultor , thanks for posting!

Interesting idea. Is there already an equivalent for a default subparser in plain argparse? I'm not doing anything different from argparse in this case here, so if it's natively supported, it would be pretty easy to add, and a lot harder if it isn't.

**Comment by Conchylicultor** [comment]
Yes, it's supported by argparse. Here is an example:

```python
import argparse


parser = argparse.ArgumentParser(
    description="Tensorflow Datasets CLI tool",
)

# Default function
parser.set_defaults(my_subparser_fn=lambda: parser.print_help())

# Register sub-command
subparser = parser.add_subparsers(title="command")

build_parser = subparser.add_parser("build", help="builc cmd.")
build_parser.set_defaults(my_subparser_fn=lambda: print("build!!"))


args = parser.parse_args([])
args.my_subparser_fn()  # No arguments: Print the parser.print_help()

args = parser.parse_args(["build"])  # Print build!!!
args.my_subparser_fn()

```

**Comment by lebrice** [comment]
Even though this works, it isn't exactly a default subparser action, right? It's simply using subparsers as a way to change the default value of an attribute, and then having to call the function yourself after parsing the args.

I'll have to experiment a little bit with this on my end, since I'm not quite sure how I'd go about adding something like this to simple-parsing without it being too far from "vanilla" argparse.

**Comment by lebrice** [comment]
Closing this for now, as I'm not exactly sure I know how to tackle this without straying too far from vanilla argparse. Let me know if you have any thoughts on this, and we can re-open this.
