### ISSUE TITLE
Support for subparser aliases

### ISSUE THREAD

**Issue by naturalethic** [lebrice/SimpleParsing#58]
**Is your feature request related to a problem? Please describe.**
Naming of subprocess commands is done automatically by introspecting the class name.  

**Describe the solution you'd like**
I'd like to be able to specify one or more aliases, specifically to allow a short version.

**Describe alternatives you've considered**
I looked into autocomplete libs but these are not reliable or easy to administer.

**Comment by lebrice** [comment]
Hello @naturalethic , sorry for the late reply!

You can use the `subparsers` utility function, passing in a dictionary mapping from subparser name to dataclass type.

Hope this helps!

**Comment by lebrice** [comment]
For example, in the [subparsers example](https://github.com/lebrice/SimpleParsing/blob/master/examples/subparsers/subparsers_example.py), you could also do the following:
```python
@dataclass
class Program:
    """Some top-level command"""
    command: Union[Train, Test] = subparsers({
         "some_train_alias": Train,
         "some_test_alias": Test,
     })
    verbose: bool = False   # log additional messages in the console.
    
    def execute(self):
        print(f"Program (verbose: {self.verbose})")
        return self.command.execute()
```
