### ISSUE TITLE
Default not displayed in the help text when no description comment exists

### ISSUE THREAD

**Issue by rggjan** [lebrice/SimpleParsing#64]
This example:
```
from dataclasses import dataclass

from simple_parsing import ArgumentParser

parser = ArgumentParser()


@dataclass
class Options:
    """These are the options"""

    foo: str = "aaa"  # Description
    bar: str = "bbb"


parser.add_arguments(Options, dest="options")

args = parser.parse_args(["--help"])
```

outputs:

```
usage: scratch.py [-h] [--foo str] [--bar str]

optional arguments:
  -h, --help  show this help message and exit

Options ['options']:
  These are the options

  --foo str   Description (default: aaa)
  --bar str
```

Why is the default value displayed for `foo`, but not for `bar`? Even when no description comment is given, it would be useful to know the default value set, I would think?

**Comment by lebrice** [comment]
Hi @rggjan , interesting issue, thanks for posting!

This might have to to do with how the `ArgumentDefaultsHelpFormatter` from argparse works, or maybe I'm doing something wrong in one of these places:
- [SimpleHelpFormatter](https://github.com/lebrice/SimpleParsing/blob/master/simple_parsing/help_formatter.py
)
- [Setting the "help" value](https://github.com/lebrice/SimpleParsing/blob/d8a22162d1c41698780bcc031eb7e3f055f72432/simple_parsing/wrappers/field_wrapper.py#L157)

I'll setup a quick test for this and get back to you! Thanks again for posting!

**Comment by lebrice** [comment]
Reopening this, the fix doesn't work seem to work anymore for python 3.9.12 and above.
