### ISSUE TITLE
default values passed to `mutable_field` aren't used properly

### ISSUE THREAD

**Issue by lebrice** [lebrice/SimpleParsing#77]
**Describe the bug**

**To Reproduce**
```python
from simple_parsing import ArgumentParser
from dataclasses import dataclass
from simple_parsing.helpers import mutable_field


@dataclass
class Foo:
    bar: int = 123


@dataclass
class Baz:
    a_foo: Foo = mutable_field(Foo, bar=111)
    b_foo: Foo = mutable_field(Foo, bar=222)


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_arguments(Baz, "baz")
    args = parser.parse_args()
    a_foo: Foo = args.baz.a_foo
    b_foo: Foo = args.baz.b_foo
    print(a_foo.bar, b_foo.bar)
```

**Expected behavior**

```console
$ python issue.py
111 222
```

**Actual behavior**
A clear and concise description of what is happening.

```console
$ python issue.py
123 123
```

**Comment by ryanai3** [comment]
@lebrice I'm running into this as well - is there a fix, or recommended workaround?

**Comment by lebrice** [comment]
Hey there @ryanai3 , I've just added a new test in this branch here, and It seems the issue was fixed: https://github.com/lebrice/SimpleParsing/blob/mutable_field_fix/test/utils/test_mutable_field.py

Would you mind sharing a code snippet or describing a bit more the kind of context you're having this error in?

Thanks!
